export const SET_USER = "SET_USER";
export const RESET_USER = "RESET_USER";
export const SET_FOLLOWERS = "SET_FOLLOWERS";
export const SET_FOLLOWING = "SET_FOLLOWING";
export const SET_NOTIFICATIONS = "SET_NOTIFICATIONS";